INSERT INTO tb_category(name) VALUES ('Livros');
INSERT INTO tb_category(name) VALUES ('Eletrônicos');
INSERT INTO tb_category(name) VALUES ('Computadores');

INSERT INTO tb_product (name, price, description, img_url, rating, specifications) VALUES ('The Lord of the Rings', 90.5, 'Lorem ipsum dolor sit amet...', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg', 4.9, 'Autor: J.R.R. Tolkien; 1216 páginas; Editora: HarperCollins');
INSERT INTO tb_product (name, price, description, img_url, rating, specifications) VALUES ('Smart TV', 2190.0, 'Lorem ipsum dolor sit amet...', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/2-big.jpg', 4.5, '50", 4K UHD, HDMI, Wi-Fi, Smart');
INSERT INTO tb_product (name, price, description, img_url, rating, specifications) VALUES ('Macbook Pro', 1250.0, 'Lorem ipsum dolor sit amet...', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/3-big.jpg', 4.8, 'Apple M1, 16GB RAM, 512GB SSD, 13" Retina');
INSERT INTO tb_product (name, price, description, img_url, rating, specifications) VALUES ('PC Gamer', 1200.0, 'Lorem ipsum dolor sit amet...', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/4-big.jpg', 4.6, 'Intel i5, 16GB RAM, RTX 3060, SSD 512GB');
INSERT INTO tb_product (name, price, description, img_url, rating, specifications) VALUES ('Rails for Dummies', 100.99, 'Lorem ipsum dolor sit amet...', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/5-big.jpg', 4.2, 'Autor: John Doe; 350 páginas; Editora: TechBooks');
INSERT INTO tb_product (name, price, description, img_url, rating, specifications) VALUES ('PC Gamer Ex', 1350.0, 'Lorem ipsum dolor sit amet...', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/6-big.jpg', 4.7, 'Ryzen 7, 32GB RAM, RTX 3070, SSD 1TB');
INSERT INTO tb_product (name, price, description, img_url, rating, specifications) VALUES ('PC Gamer X', 1350.0, 'Lorem ipsum dolor sit amet...', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/7-big.jpg', 4.3, 'Intel i7, 16GB RAM, GTX 1660 Super, SSD 512GB');
INSERT INTO tb_product (name, price, description, img_url, rating, specifications) VALUES ('PC Gamer Alfa', 1850.0, 'Lorem ipsum dolor sit amet...', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/8-big.jpg', 4.9, 'Ryzen 9, 32GB RAM, RTX 3080 Ti, SSD 2TB');
INSERT INTO tb_product (name, price, description, img_url, rating, specifications) VALUES ('PC Gamer Tera', 1950.0, 'Lorem ipsum dolor sit amet...', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/9-big.jpg', 4.8, 'Intel i9, 64GB RAM, RTX 3090 Ti, SSD 2TB');
INSERT INTO tb_product (name, price, description, img_url, rating, specifications) VALUES ('PC Gamer Y', 1700.0, 'Lorem ipsum dolor sit amet...', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/10-big.jpg', 4.1, 'Ryzen 5, 16GB RAM, GTX 1650 Super, SSD 256GB');
INSERT INTO tb_product (name, price, description, img_url, rating, specifications) VALUES ('PC Gamer Nitro', 1450.0, 'Lorem ipsum dolor sit amet...', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/11-big.jpg', 4.6,'Intel i5-10400F; GTX 1660; SSD 480GB; Gabinete RGB');
INSERT INTO tb_product (name, price, description, img_url, rating, specifications) VALUES ('PC Gamer Card', 1850.0, 'Lorem ipsum dolor sit amet...', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/12-big.jpg', 4.7, 'Ryzen 7; RTX 3060; SSD 1TB; Fonte 600W');
INSERT INTO tb_product (name, price, description, img_url, rating, specifications) VALUES ('PC Gamer Plus', 1350.0, 'Lorem ipsum dolor sit amet...', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/13-big.jpg', 4.6, 'Intel i7-10700; RTX 3070 Ti; SSD 1TB; Water Cooler');
INSERT INTO tb_product (name, price, description, img_url, rating, specifications) VALUES ('PC Gamer Hera', 2250.0, 'Lorem ipsum dolor sit amet...', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/14-big.jpg', 4.8, 'Ryzen 9; RTX 3080; SSD NVMe 2TB; Gabinete Vidro Temperado');
INSERT INTO tb_product (name, price, description, img_url, rating, specifications) VALUES ('PC Gamer Weed', 2200.0, 'Lorem ipsum dolor sit amet...', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/15-big.jpg', 4.7, 'Intel i9-11900K; RTX 3070; SSD NVMe 1TB; Fonte Modular');
INSERT INTO tb_product (name, price, description, img_url, rating, specifications) VALUES ('PC Gamer Max', 2340.0, 'Lorem ipsum dolor sit amet...', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/16-big.jpg', 4.9, 'Ryzen 7; RTX 3090; SSD NVMe 2TB; Water Cooler Duplo');
INSERT INTO tb_product (name, price, description, img_url, rating, specifications) VALUES ('PC Gamer Turbo', 1280.0, 'Lorem ipsum dolor sit amet...', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/17-big.jpg', 4.5, 'Intel i5-11400F; GTX 1660 Super; SSD SATA 480GB');
INSERT INTO tb_product (name, price, description, img_url, rating, specifications) VALUES ('PC Gamer Hot', 1450.0, 'Lorem ipsum dolor sit amet...', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/18-big.jpg', 4.3, 'Ryzen 5; GTX 1650; SSD SATA 240GB');
INSERT INTO tb_product (name, price, description, img_url, rating, specifications) VALUES ('PC Gamer Ez', 1750.0, 'Lorem ipsum dolor sit amet...', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/19-big.jpg', 4.6, 'Intel i7-11700F; RTX 3060 Ti; SSD NVMe 1TB');
INSERT INTO tb_product (name, price, description, img_url, rating, specifications) VALUES ('PC Gamer Tr', 1650.0, 'Lorem ipsum dolor sit amet...', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/20-big.jpg', 4.2, 'Ryzen 5; GTX 1660 Super; SSD SATA 480GB');
INSERT INTO tb_product (name, price, description, img_url, rating, specifications) VALUES ('PC Gamer Tx', 1680.0, 'Lorem ipsum dolor sit amet...', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/21-big.jpg', 4.1, 'Intel i5-10400F; GTX 1650 Super; SSD SATA 240GB');
INSERT INTO tb_product (name, price, description, img_url, rating, specifications) VALUES ('PC Gamer Er', 1850.0, 'Lorem ipsum dolor sit amet...', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/22-big.jpg', 4.3, 'Ryzen 7; RTX 3060 Ti; SSD NVMe 1TB');
INSERT INTO tb_product (name, price, description, img_url, rating, specifications) VALUES ('PC Gamer Min', 2250.0, 'Lorem ipsum dolor sit amet...', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/23-big.jpg', 4.8, 'Intel i9-11900K; RTX 3080 Ti; SSD NVMe 2TB');
INSERT INTO tb_product (name, price, description, img_url, rating, specifications) VALUES ('PC Gamer Boo', 2350.0, 'Lorem ipsum dolor sit amet...', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/24-big.jpg', 4.9, 'Ryzen Threadripper; RTX A6000; SSD NVMe Gen4 2TB');
INSERT INTO tb_product (name, price, description, img_url, rating, specifications) VALUES ('PC Gamer Foo', 4170.0, 'Lorem ipsum dolor sit amet...', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/25-big.jpg', 5.0, 'Xeon W-3175X; Quadro RTX8000; SSD NVMe Gen4 4TB');

INSERT INTO tb_product_category (product_id, category_id) VALUES (1, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (2, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (2, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (3, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (4, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (5, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (6, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (7, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (8, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (9, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (10, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (11, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (12, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (13, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (14, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (15, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (16, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (17, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (18, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (19, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (20, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (21, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (22, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (23, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (24, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (25, 3);

INSERT INTO tb_user (name, email, phone, password, birth_date) VALUES ('Maria Brown', 'maria@gmail.com', '988888888', '123456', '2001-07-25');
INSERT INTO tb_user (name, email, phone, password, birth_date) VALUES ('Alex Green', 'alex@gmail.com', '977777777', '123456', '1987-12-13');

INSERT INTO tb_order (moment, status, client_id) VALUES (TIMESTAMP WITH TIME ZONE '2022-07-25T13:00:00Z', 1, 1);
INSERT INTO tb_order (moment, status, client_id) VALUES (TIMESTAMP WITH TIME ZONE '2022-07-29T15:50:00Z', 3, 2);
INSERT INTO tb_order (moment, status, client_id) VALUES (TIMESTAMP WITH TIME ZONE '2022-08-03T14:20:00Z', 0, 1);

INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (1, 1, 2, 90.5);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (1, 3, 1, 1250.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (2, 3, 1, 1250.0);
INSERT INTO tb_order_item (order_id, product_id, quantity, price) VALUES (3, 1, 1, 90.5);

INSERT INTO tb_payment (order_id, moment) VALUES (1, TIMESTAMP WITH TIME ZONE '2022-07-25T15:00:00Z');
INSERT INTO tb_payment (order_id, moment) VALUES (2, TIMESTAMP WITH TIME ZONE '2022-07-30T11:00:00Z');